exclude: [_posts/blog]

### Site info:
title:
tagline:
author: Fmajor
email: wujinnnnn@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "/freshman" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1" # the base hostname & protocol for your site
locale: en_US
headerFig: "/images/header-long.png"
background: "/images/background.png"
postsMedia: "/media/posts"

### Personal info and site tools info:
twitter_username:
github_username: Fmajor
disqus_shortname: fmajor
favicon:     "/images/favicon.ico"
aboutme: "we are dead stars, observing our companions in the sky." # these are shown on aboutme-sidebar.
aboutme_photo: "/images/photo.jpg" # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "友链"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: Freshman21
      href: http://yulijia.net/freshman21
      title: Another Jekyll blog theme
    - name: author's website
      href: http://yulijia.net/
      title: Lijia Yu's website

### Build settings
markdown: kramdown
# highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"
      author: "Fmajor"
      category: "blog"


collections:
    blog:
        output: false
        #permalink: /oldPosts/:path/


