exclude: [
    _posts/2013-10-10-milu.md,
    _posts/2014-12-13-simple-post.md,
    _posts/2014-12-18-how-to-install.md,
    _posts/2014-12-19-freshman21-structure.md,
    _posts/2014-12-19-how-to-set-the-config-file.md,
    _posts/2015-03-31-2.0version.md
]

### Site info:
title:
tagline:
author: Fmajor
email: wujinnnnn@gmail.com
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "/freshman" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1" # the base hostname & protocol for your site
locale: en_US
headerFig: "/images/header-long.png"
background: "/images/background.png"
postsMedia: "/media/posts"

### Personal info and site tools info:
twitter_username:
github_username: Fmajor
disqus_shortname: fmajor
favicon: "/images/favicon.ico"
aboutme: "我们是逝去的恒星,</br>仰望着天上的同伴" # these are shown on aboutme-sidebar.
aboutme_photo: "/images/photo.jpg" # your photo.


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "友链"
      Categories: "分类目录"
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签"
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Thanks: "致谢"


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: 云居
      href: http://gerry.lamost.org/blog/
      title: 云居
    - name: 剧毒姐姐
      title: 剧毒姐姐
      href: http://sistoxic.com/
    - name: 星海流光
      title: 星海流光
      href: http://cma.lamost.org/
    - name: 苍宇狂想
      title: 苍宇狂想
      href: http://eagle.lamost.org/
    - name: 蘑菇天文馆
      title: 蘑菇天文馆
      href: http://blog.atr.me/

### Build settings
markdown: kramdown
# highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "posts"
      author: "Fmajor"
      category: "blog"


collections:
    blog:
        output: false
        #permalink: /oldPosts/:path/


